<?xml version="1.0"?>
<package format="3">
  <name>rvt_live_inference</name>
  <version>0.1.0</version>
  <description>ROS2 live wrapper for the official RVT event-camera detector.</description>
  <maintainer email="hybridneuroperception@example.invalid">HybridNeuroPerception</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>jetson_evt21_decoder</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
